### PR TITLE
fix parsing / printing of IPv6 addresses in URIs

### LINKED ISSUE #163: IPv6 addresses in square brackets are parsed incorrectly
"Connect  over HTTPS to port 8443 on 2001:db8:ff::1" is `https://[2001:db:ff::1]:8443/...`.

`Uri.of_string`, however, completely misunderstands it and thinks the URI has no authority part at all.

```ocaml
utop # let u = Uri.of_string "https://[2001:db8:ff::1]:8443/~user/page.html" ;;
val u : Uri.t = https:///%5B2001:db8:ff::1%5D:8443/~user/page.html

utop # Uri.path u ;;
- : string = "%5B2001:db8:ff::1%5D:8443/~user/page.html"

utop # Uri.host u ;;
- : string option = Some ""
```

### PR DESCRIPTION
**Pull request by anmonteiro**
fixes #163

### CODE REVIEW

**Comment by bikallem** [comment]
I recently came across the same issue referenced by this PR. 

Are the CI failures related to this PR? From the tests, it implementation looks okay.

**Comment by tmcgilchrist** [comment]
@anmonteiro if you rebase this the build should pass. 
see https://github.com/tmcgilchrist/ocaml-uri/pull/2/checks?check_run_id=12145037435

**Review by tmcgilchrist — COMMENTED** [review]
These changes look reasonable to me. Just noting this would be an API breaking change and needs a major version bump.

**Comment by bernhardkaindl** [comment]
@avsm _We likewise had to take this change as patch into XenServer as we need it working too_!

BTW:
* Pau also manually tested it to work as expected using an utop session:
  ```ml
  # #require "uri" ;;
  # let uri = Uri.of_string "http://[::1]";;
  # Uri.path uri ;;
  - : string = ""
  # Uri.host uri ;;
  ```
I hope this helps you to review it for merging.

**Comment by benjamreis** [comment]
FYI I backported this fix in a previous version of the lib also presenting the IPv6 URI bug and it has indeed solved it.
Eager to see this PR merged and to get the fix from upstream! :+1:

File: lib/uri.ml [hunk 1]
```diff
@@ -707,11 +692,11 @@ let with_scheme uri =
...
 
-let host uri = get_decoded_opt uri.host
-let with_host uri =
-  function
-  |Some host -> { uri with host=Some (Pct.cast_decoded host) }
-  |None -> { uri with host=None }
+let host uri =
+  match uri.host with
+  | None -> None
+  | Some (`Ipv4_literal h | `Ipv6_literal h) -> Some h
```
Comment (psafont) [inline lib/uri.ml:698]: It's not clear to me whether the ipv6 here should be returned surrounded by square brackets. @mseri thinks it should, it would fix an issue in cohttp: https://github.com/mirage/ocaml-cohttp/issues/997

Comment (dinosaure) [reply lib/uri.ml:698]: It seems correct, the domain part of email addresses also use brackets to delimit user-defined domains or IPv6 address.

Comment (bernhardkaindl) [reply lib/uri.ml:698]: Yes, as psafont mentioned above, @mseri proposed that it should be fixed here in the uri package in his comment https://github.com/mirage/ocaml-cohttp/issues/997#issuecomment-1721364362:
> I think this should be fixed in the uri package, then all dependent libraries would benefit directly from the fix.

@anmonteiro, can you have a look and update this PR to fix mirage/ocaml-cohttp#997?

Hier is the link to the code location in the full review diff:
https://github.com/mirage/ocaml-uri/pull/169/files#r1330212509

I don't know Ocaml, but a few lines above it, there is similar code (just with `host` instead of `h`), so maybe that can be used as a starting point for updating this function:
```ml
  |Some (`Ipv4_literal host) -> Buffer.add_string buf host
  |Some (`Ipv6_literal host) ->
      Buffer.add_char buf '[';
      Buffer.add_string buf host;
      Buffer.add_char buf ']'
  );
```

**Comment by dinosaure** [comment]
It seems that this PR is highly required but it breaks the `uri` behavior. From the RFC point-of-view, the fix seems right as explained in #169. I need to convince myself more to merge & cut a release due to the implication that this PR can have on the OCaml ecosystem. However, I consider to merge it as soon as I can.

File: lib/uri.ml [hunk 2]
```diff
@@ -1025,10 +981,12 @@ module Parser = struct
...
   let host =
-    lift
-      (fun s -> Pct.decode (Pct.cast_encoded s))
-      (choice
-         [ reg_name; ipv4_address; ipv6_address (* | ipv4_literal TODO *) ])
+    choice
+      [ ipv4_address >>| (fun h -> `Ipv4_literal h)
+      ; ipv6_address >>| (fun h -> `Ipv6_literal h)
+      ; reg_name >>| (fun s -> `Host (Pct.decode (Pct.cast_encoded s)))
+      (* ipv4_literal TODO *)
```
Comment (dinosaure) [inline lib/uri.ml:988]: Not sure about this remaining TODO. From the RFC, we talk about `IP-literal` which includes `IPv6address` or `IPvFuture`. We probably should change it to: `TODO: IPvFuture` which seems to not be handled by this PR.
